### ISSUE TITLE
Uncaught ReferenceError: disableBuilder is not defined

### ISSUE THREAD

**Issue by hawkw** [florianb/atom-gradle-ci#11]
This issue occurs every time I open a file without an associated Gradle project.

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.5
**Thrown From**: [gradle-ci](https://github.com/florianb/atom-gradle-ci) package, v1.0.1
### Stack Trace

Uncaught ReferenceError: disableBuilder is not defined

```
At /Users/hawk/.atom/packages/gradle-ci/lib/gradle-ci-builder.coffee:238

ReferenceError: disableBuilder is not defined
    at GradleCiBuilder.checkVersion (/Users/hawk/.atom/packages/gradle-ci/lib/gradle-ci-builder.coffee:238:16)
    at /Users/hawk/.atom/packages/gradle-ci/lib/gradle-ci-builder.coffee:3:61
    at /Users/hawk/.atom/packages/gradle-ci/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:736:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:997:16)
    at Socket.<anonymous> (child_process.js:1166:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at Pipe.close (net.js:464:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".gradle",
      ".idea",
      ".iml",
      ".ipr",
      ".iws",
      ".sublime-workspace"
    ],
    "themes": [
      "spacegray-dark-ui",
      "base16-ocean-dark-spacegray-lighter-invisibles"
    ],
    "projectHome": "/Users/hawk/Development",
    "disabledPackages": [
      "tidy-markdown",
      "clojure-eval-in-repl",
      "r-exec",
      "autocomplete-haskell",
      "scala-worksheet",
      "atom-live-grammar-reload",
      "markdown-preview-katex",
      "haskell-pointfree",
      "linter-scalac",
      "ide-haskell"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-bibtex, v0.6.0
base16-ocean-dark-spacegray-lighter-invisibles, v0.3.0
color-picker, v2.0.11
docblockr, v0.7.3
editorconfig, v1.1.1
file-icons, v1.6.9
gradle-ci, v1.0.1
haskell-ghc-mod, v0.8.14
language-gitignore, v0.2.0
language-gradle, v0.0.3
language-groovy, v0.4.0
language-haskell, v1.4.1
language-latex, v0.6.1
language-lisp, v0.1.2
language-r, v0.2.0
language-rust, v0.4.4
language-scala, v1.1.3
latex, v0.25.1
latexer, v0.2.4
linter, v1.4.3
linter-chktex, v1.0.0
linter-clang, v3.1.3
linter-clojure, v0.0.5
linter-hlint, v0.4.2
linter-javac, v1.1.0
linter-pep8, v1.0.1
linter-rust, v0.2.8
markdown-preview-opener, v0.1.1
minimap, v4.13.2
pigments, v0.12.0
project-manager, v1.16.0
racer, v0.17.1
regex-railroad-diagram, v0.8.4
scala-format, v0.1.8
spacegray-dark-ui, v0.12.0
tabs-to-spaces, v0.11.1
travis-ci-status, v0.16.0
wakatime, v4.0.16

# Dev
No dev packages
```

**Comment by florianb** [comment]
Thanks for opening the issue.
