### ISSUE TITLE
Gradle CI doesn't like it when there are spaces in the path leading to build.gradle

### ISSUE THREAD

**Issue by chefhoobajoob** [florianb/atom-gradle-ci#14]
One of the folders in the path leading to my build.gradle file is named `Visual Studio 2013`, and this causes gradle-ci to stumble. It's likely just an embedded quotes problem:

```
Ooops. Something went wrong.
Command failed: C:\Windows\system32\cmd.exe /s /c "C:\Users\hoobajoob\Documents\Visual Studio 2013\Projects\project-x\gradlew.bat tasks"
'C:\Users\hoobajoob\Documents\Visual' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed: C:\Windows\system32\cmd.exe /s /c "C:\Users\hoobajoob\Documents\Visual Studio 2013\Projects\project-x\gradlew.bat tasks"
'C:\Users\hoobajoob\Documents\Visual' is not recognized as an internal or external command,
operable program or batch file.
    at ChildProcess.exithandler (child_process.js:215:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by chefhoobajoob** [comment]
Hm - actually, this may be coming from `build-gradle`, not `gradle-ci`. Verifying...

**Comment by florianb** [comment]
Thanks for reporting @chefhoobajoob - i guess the path should be escaped (f.e. with a prepending caret `like^ this`). Unfortunately i can't test it - since i have currently no windows instance up.

**Comment by chefhoobajoob** [comment]
Confirmed: this behavior is coming from `atom-build-gradle`, not `gradle-ci`. Might be worth checking into, though.  Thanks!

**Comment by florianb** [comment]
You are welcome - don't hesitate to come back if there's something i could change.
