### ISSUE TITLE
being told to report error by atom

### ISSUE THREAD

**Issue by PlasmaDev5** [florianb/atom-gradle-ci#2]
Not sure what happened but its not preventing me programming just keep popping up report error notifications.

**Atom Version**: 0.184.0
**System**: Microsoft Windows 10 Pro Technical Preview
**Thrown From**: [gradle-ci](https://github.com/florianb/atom-gradle-ci) package, v0.2.3
### Stack Trace

Uncaught Error: watch ENOENT

```
At fs.js:1189

Error: watch ENOENT
    at exports._errnoException (util.js:753:11)
    at FSWatcher.start (fs.js:1189:11)
    at Object.fs.watch (fs.js:1215:11)
    at EventEmitter.FSWatcher._watch (C:\Users\josh\.atom\packages\gradle-ci\node_modules\chokidar\index.js:246:18)
    at EventEmitter.FSWatcher._handleFile (C:\Users\josh\.atom\packages\gradle-ci\node_modules\chokidar\index.js:280:8)
    at C:\Users\josh\.atom\packages\gradle-ci\node_modules\chokidar\index.js:356:33
    at FSReqWrap.oncomplete (fs.js:100:15)
```
### Commands

```
  2x -9:33.2 core:save (atom-text-editor.editor.is-focused)
     -7:18.5 core:confirm (atom-text-editor.editor.mini)
     -0:37.9 core:move-right (atom-text-editor.editor)
  2x -0:37.2 editor:newline (atom-text-editor.editor)
     -0:16.4 core:paste (atom-text-editor.editor)
     -0:15.8 core:save (atom-text-editor.editor)
     -0:12.3 core:move-left (atom-text-editor.editor)
     -0:11.7 editor:newline (atom-text-editor.editor)
     -0:11.1 snippets:next-tab-stop (atom-text-editor.editor)
     -0:11.1 snippets:expand (atom-text-editor.editor)
     -0:11.1 editor:indent (atom-text-editor.editor)
  2x -0:10.5 core:move-up (atom-text-editor.editor)
     -0:09.3 editor:newline (atom-text-editor.editor)
  2x -0:08.5 core:move-up (atom-text-editor.editor)
     -0:07.7 core:save (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "gradle-ci": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus-async, v0.22.0
build, v0.23.4
gradle-ci, v0.2.3
language-glsl, v1.0.1
language-opencl, v0.1.0

# Dev
No dev packages
```

**Comment by florianb** [comment]
@dragonCASTjosh - thank you for your report. I'll try to pin down and fix that. :beer:

**Comment by florianb** [comment]
That bug was caused by the use of the chokidar-library and its file-watcher. During the pending rewrite of the package, i take chokidar out.

**Comment by florianb** [comment]
I removed the chokidar-dependency. Please be patient, i'm still working on a 1.x-release which will change the build-invokation.
