### ISSUE TITLE
Failed to activate the gradle-ci package

### ISSUE THREAD

**Issue by sarvex** [florianb/atom-gradle-ci#3]
[Enter steps to reproduce below:]
1. Install the gradle-ci package and the following error is shown

**Atom Version**: 0.187.0
**System**: Windows 8.1
**Thrown From**: [gradle-ci](https://github.com/florianb/atom-gradle-ci) package, v0.2.3
### Stack Trace

Failed to activate the gradle-ci package

```
At Arguments to path.resolve must be strings

TypeError: Arguments to path.resolve must be strings
  at Object.win32.resolve (path.js:112:13)
  at Object.realpath (fs.js:1444:18)
  at Object.fs.realpath (ATOM_SHELL_ASAR.js:260:25)
  at EventEmitter.FSWatcher._handle (C:\Users\Sarvex\.atom\packages\gradle-ci\node_modules\chokidar\index.js:342:13)
  at EventEmitter.<anonymous> (C:\Users\Sarvex\.atom\packages\gradle-ci\node_modules\chokidar\index.js:417:17)
  at Array.forEach (native)
  at EventEmitter.FSWatcher.add (C:\Users\Sarvex\.atom\packages\gradle-ci\node_modules\chokidar\index.js:416:9)
  at Object.exports.watch (C:\Users\Sarvex\.atom\packages\gradle-ci\node_modules\chokidar\index.js:455:33)
  at new GradleCiBuilder (C:\Users\Sarvex\.atom\packages\gradle-ci\lib\gradle-ci-builder.coffee:48:32)
  at Object.module.exports.activate (C:\Users\Sarvex\.atom\packages\gradle-ci\lib\gradle-ci.coffee:16:17)
  at Package.module.exports.Package.activateNow (C:\Users\Sarvex\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:240:19)
  at C:\Users\Sarvex\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:221:30
  at Package.module.exports.Package.measure (C:\Users\Sarvex\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (C:\Users\Sarvex\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Sarvex\AppData\Local\atom\app-0.187.0\resources\app\src\package-manager.js:465:21)
  at C:\Users\Sarvex\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:268:29
  at exit (C:\Users\Sarvex\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (C:\Users\Sarvex\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\Sarvex\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```
### Commands

```
  2x -35:41.8 core:confirm (atom-text-editor.editor.mini)
  4x -33:12.5 core:backspace (atom-text-editor.editor.mini)
     -33:09.6 core:confirm (atom-text-editor.editor.mini)
  3x -32:46.5 core:backspace (atom-text-editor.editor.mini)
     -32:44.8 core:confirm (atom-text-editor.editor.mini)
     -30:55.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "autoHideMenuBar": true,
    "followSymlinks": true,
    "projectHome": "c:\\Users\\Sarvex\\Workspace"
  },
  "gradle-ci": {}
}
```
### Installed Packages

``` coffee
# User
gradle-ci, v0.2.3
language-d, v3.1.0
language-elm, v0.4.1
language-erlang, v2.0.0
language-idl, v0.0.8
language-r, v0.1.1
language-slm, v0.5.0
language-x86, v0.1.0
linter, v0.12.0
linter-clang, v2.25.1
linter-erlc, v0.2.0
vim-mode, v0.38.0

# Dev
No dev packages
```

**Comment by wangddff** [comment]
I also met this issue, who can help

**Comment by RioRizkyRainey** [comment]
I also met this issue

**Comment by raanand-home** [comment]
also

**Comment by florianb** [comment]
I'm sorry for any inconvenience - I'll examine that issue after porting the package to Atom 1.x.

**Comment by florianb** [comment]
This issue has been resolved, but there are pending changes to the build-invokation. Please standby for the 1.x-release.
