### ISSUE TITLE
Failed to load the gradle-ci package

### ISSUE THREAD

**Issue by hawkw** [florianb/atom-gradle-ci#8]
This occurs immediately after updating the package.

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [gradle-ci](https://github.com/florianb/atom-gradle-ci) package, v0.2.5
### Stack Trace

Failed to load the gradle-ci package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/hawk/.atom/packages/gradle-ci/node_modules/atom-panetastic/js/panetastic.js:5:199)
    at /Users/hawk/.atom/packages/gradle-ci/node_modules/atom-panetastic/js/panetastic.js:10:5
    at Object.<anonymous> (/Users/hawk/.atom/packages/gradle-ci/node_modules/atom-panetastic/js/panetastic.js:105:5)
    at Object.<anonymous> (/Users/hawk/.atom/packages/gradle-ci/node_modules/atom-panetastic/js/panetastic.js:109:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/hawk/.atom/packages/gradle-ci/lib/gradle-ci-builder.coffee:9:16)
    at Object.<anonymous> (/Users/hawk/.atom/packages/gradle-ci/lib/gradle-ci-builder.coffee:195:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```
### Commands

```
     -0:47.8.0 core:cut (atom-text-editor.editor.is-focused)
     -0:44.5.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:44.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:44.3.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:44.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:44.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:42.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:38.5.0 core:cut (atom-text-editor.editor.is-focused)
     -0:38.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:34.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:34.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:34.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:34.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:33.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:33.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:31.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-ocean-dark-spacegray-lighter-invisibles.theme-spacegray-dark-ui)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".gradle",
      ".idea",
      ".iml",
      ".ipr",
      ".iws",
      ".sublime-workspace"
    ],
    "themes": [
      "spacegray-dark-ui",
      "base16-ocean-dark-spacegray-lighter-invisibles"
    ],
    "projectHome": "/Users/hawk/Development",
    "disabledPackages": [
      "tidy-markdown",
      "clojure-eval-in-repl",
      "r-exec",
      "autocomplete-haskell",
      "scala-worksheet",
      "atom-live-grammar-reload",
      "markdown-preview-katex",
      "haskell-pointfree",
      "linter-scalac",
      "ide-haskell"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.11
autocomplete-bibtex, v0.6.0
base16-ocean-dark-spacegray-lighter-invisibles, v0.3.0
color-picker, v2.0.11
docblockr, v0.7.3
editorconfig, v1.1.1
file-icons, v1.6.7
gradle-ci, v0.2.5
haskell-ghc-mod, v0.8.12
language-gitignore, v0.2.0
language-gradle, v0.0.3
language-groovy, v0.4.0
language-haskell, v1.3.1
language-latex, v0.6.1
language-lisp, v0.1.2
language-r, v0.2.0
language-rust, v0.4.4
language-scala, v1.1.3
latex, v0.25.1
latexer, v0.2.4
linter, v1.4.3
linter-chktex, v1.0.0
linter-clang, v3.1.3
linter-clojure, v0.0.5
linter-hlint, v0.4.2
linter-javac, v1.1.0
linter-pep8, v1.0.1
linter-rust, v0.2.8
markdown-preview-opener, v0.1.1
minimap, v4.13.1
pigments, v0.11.0
project-manager, v1.15.11
racer, v0.17.1
regex-railroad-diagram, v0.8.4
scala-format, v0.1.8
spacegray-dark-ui, v0.12.0
tabs-to-spaces, v0.11.1
travis-ci-status, v0.16.0
wakatime, v4.0.13

# Dev
No dev packages
```

**Comment by florianb** [comment]
@hawkw: Thanks for reporting this issue - i'm working on a solution.

**Comment by hawkw** [comment]
Good luck! Let me know if you need more information.

**Comment by florianb** [comment]
Thanks! :)

**Comment by florianb** [comment]
The package should now load without errors, but be aware, i'm still working on a 1.x-release.
