### ISSUE TITLE
Uncaught ReferenceError: directoryChangedEvent is not defined

### ISSUE THREAD

**Issue by lwis** [florianb/atom-gradle-ci#9]
1. Enable the plugin
2. Run build

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [gradle-ci](https://github.com/florianb/atom-gradle-ci) package, v0.2.8
### Stack Trace

Uncaught ReferenceError: directoryChangedEvent is not defined

```
At /Users/Lewis/.atom/packages/gradle-ci/lib/gradle-ci-builder.coffee:54

ReferenceError: directoryChangedEvent is not defined
  at /Users/Lewis/.atom/packages/gradle-ci/lib/gradle-ci-builder.coffee:54:12
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PathWatcher.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:340:34)
  at HandleWatcher.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:132:26)
  at emitThree (events.js:102:20)
  at HandleWatcher.emit (events.js:172:7)
  at HandleWatcher.onEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:60:23)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:20:41

```
### Commands

```
     -6:48.1.0 core:save (atom-text-editor.editor.is-focused)
     -6:43 core:backspace (atom-text-editor.editor.is-focused)
  3x -6:41.9.0 core:save (atom-text-editor.editor.is-focused)
     -4:11.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:11 core:save (atom-text-editor.editor.is-focused)
     -4:09.8.0 core:copy (atom-text-editor.editor.is-focused)
     -3:54.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:52.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:52.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:37.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:37.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -2:56.2.0 markdown-pdf:convert (atom-text-editor.editor.is-focused)
     -2:16.9.0 core:copy (atom-text-editor.editor.is-focused)
     -2:15.1.0 core:paste (atom-text-editor.editor.is-focused)
     -2:14.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:20 core:select-all (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "color-picker"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "gradle-ci": {
    "runTasks": "build",
    "triggerBuildAfterSave": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.11
atom-material-ui, v0.6.0
autocomplete-paths, v1.0.2
autocomplete-plus-python-jedi, v0.3.6
build, v0.44.0
custom-title, v1.0.1
file-icons, v1.6.7
flex-tool-bar, v0.5.0
git-history, v3.0.1
gradle-ci, v0.2.8
jshint, v1.4.0
language-docker, v1.1.3
language-groovy, v0.4.0
language-log, v0.6.0
linter, v1.4.3
linter-coffeelint, v1.0.2
linter-csslint, v1.0.5
linter-javac, v1.1.0
linter-pylama, v0.1.5
linter-tidy, v1.0.1
linter-xmllint, v0.0.7
markdown-pdf, v1.3.9
pretty-json, v0.4.1
project-manager, v1.15.11
save-session, v0.15.7
svn, v0.0.8
tabs-to-spaces, v0.11.1
tool-bar, v0.1.8
trailing-spaces, v0.3.2
travis-ci-status, v0.16.0
webbox-color, v0.5.8

# Dev
No dev packages
```

**Comment by florianb** [comment]
Thanks for the report - i'm working on it.

**Comment by florianb** [comment]
This issue should be resolved. Please be patient, i'm still working on a 1.x-release which will change at least the build-incokation.
